---
Name: skeletor
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - "app/client/dist/editor.css"
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "app/client/dist/cms.css"
Skeletor\Extensions\SiteConfigExtension:
  noindex_domains:
    - localhost
    - .plasticstudio.co
LeKoala\DebugBar\DebugBar:
  check_local_ip: false

---
Only:
  environment: "dev"
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      LogFileHandler: [pushHandler, ["%$LogFileHandler"]]
  LogFileHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "./silverstripe.log"
      - "info"

# app/_config/config.yml
SilverStripe\Admin\LeftAndMain:
  help_links:
    # Add a new link
    'Shopify Orders': 'https://emmas-sandbox-store.myshopify.com/admin/orders?selectedView=all'